import {
  Inter,
  Delius_Swash_Caps,
  Kolker_Brush,
  Kumbh_Sans,
  Klee_One,
  DM_Serif_Text,
  Khula,
  Paytone_One,
  Gilda_Display,
  Livvic,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const delius = Delius_Swash_Caps({
  subsets: ["latin"],
  variable: "--delius",
  weight: "400",
});
const kolker = Kolker_Brush({
  subsets: ["latin"],
  variable: "--kolker",
  weight: "400",
});
const gilda = Gilda_Display({
  subsets: ["latin"],
  variable: "--gilda",
  weight: "400",
});
const dmSerif = DM_Serif_Text({
  subsets: ["latin"],
  variable: "--dmSerif",
  weight: "400",
});
const paytone = Paytone_One({
  subsets: ["latin"],
  variable: "--paytone",
  weight: "400",
});
const klee = Klee_One({
  subsets: ["latin"],
  variable: "--klee",
  weight: ["400", "600"],
});
const kumbh = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--kumbh",
  weight: ["100", "200", "300", "400", "500"],
});
const khula = Khula({
  subsets: ["latin"],
  variable: "--khula",
  weight: ["300", "400", "600", "700", "800"],
});
const livic = Livvic({
  subsets: ["latin"],
  variable: "--livic",
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${dmSerif.variable} ${livic.variable} ${gilda.variable} ${paytone.variable} ${khula.variable} ${inter.variable} ${delius.variable} ${kolker.variable} ${kumbh.variable} ${klee.variable}`}
    >
      <body className="">{children}</body>
    </html>
  );
}
